/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subjects */
        get: operations["list_subjects_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{slug}/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Path */
        get: operations["get_path_subjects__slug__path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson */
        get: operations["get_lesson_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quiz */
        get: operations["get_quiz_lessons__lesson_id__quiz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}/quiz/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Quiz */
        post: operations["submit_quiz_lessons__lesson_id__quiz_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Skills */
        get: operations["my_skills_me_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Practice Next */
        get: operations["practice_next_practice_next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Practice Submit */
        post: operations["practice_submit_practice_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_chat_sessions__session_id__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/math/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Math */
        post: operations["submit_math_math_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerSubmission */
        AnswerSubmission: {
            /** Question Id */
            question_id: number;
            /** Answer */
            answer: string;
        };
        /** Body_submit_math_math_submit_post */
        Body_submit_math_math_submit_post: {
            /**
             * Image
             * Format: binary
             */
            image: string;
            /** Question Id */
            question_id: number;
        };
        /** ChatMessageRequest */
        ChatMessageRequest: {
            /** Content */
            content: string;
        };
        /** ChatMessageResponse */
        ChatMessageResponse: {
            /** Reply */
            reply: string;
            /**
             * Done
             * @default false
             */
            done: boolean;
            /** Feedback */
            feedback?: string | null;
        };
        /**
         * ChatModeEnum
         * @enum {string}
         */
        ChatModeEnum: "english_convo" | "science_explain";
        /** ChatSessionCreateRequest */
        ChatSessionCreateRequest: {
            /** Lesson Id */
            lesson_id: number;
            mode: components["schemas"]["ChatModeEnum"];
        };
        /** ChatSessionCreateResponse */
        ChatSessionCreateResponse: {
            /** Session Id */
            session_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LessonDetail */
        LessonDetail: {
            lesson: components["schemas"]["LessonOut"];
            /** Sections */
            sections: components["schemas"]["LessonSectionOut"][];
        };
        /** LessonOut */
        LessonOut: {
            /** Id */
            id: number;
            /** Subject Id */
            subject_id: number;
            /** Order Index */
            order_index: number;
            /** Title */
            title: string;
            /** Objective */
            objective: string;
        };
        /** LessonSectionOut */
        LessonSectionOut: {
            /** Id */
            id: number;
            /** Order Index */
            order_index: number;
            /** Heading */
            heading: string;
            /** Body Md */
            body_md: string;
        };
        /**
         * LessonStatusEnum
         * @enum {string}
         */
        LessonStatusEnum: "locked" | "unlocked" | "completed";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MathSubmitResponse */
        MathSubmitResponse: {
            verdict: components["schemas"]["MathVerdictEnum"];
            /** Feedback */
            feedback: string;
            /** Extracted */
            extracted?: Record<string, never> | null;
        };
        /**
         * MathVerdictEnum
         * @enum {string}
         */
        MathVerdictEnum: "correct" | "incorrect" | "unreadable";
        /** PathNode */
        PathNode: {
            /** Lesson Id */
            lesson_id: number;
            /** Order */
            order: number;
            /** Title */
            title: string;
            status: components["schemas"]["LessonStatusEnum"];
            /** Score */
            score?: number | null;
        };
        /** PracticeSetOut */
        PracticeSetOut: {
            /** Questions */
            questions: components["schemas"]["QuestionPublic"][];
        };
        /** PracticeSubmitRequest */
        PracticeSubmitRequest: {
            /** Answers */
            answers: Record<string, never>[];
        };
        /** PracticeSubmitResponse */
        PracticeSubmitResponse: {
            /** Results */
            results: components["schemas"]["QuestionResult"][];
            /** Skill Breakdown */
            skill_breakdown: components["schemas"]["SkillBreakdownItem"][];
        };
        /**
         * QuestionPublic
         * @description Question as served to a student — correct_answer is never included.
         */
        QuestionPublic: {
            /** Id */
            id: number;
            /** Lesson Id */
            lesson_id: number;
            skill_tag: components["schemas"]["SkillTagEnum"];
            qtype: components["schemas"]["QuestionTypeEnum"];
            /** Body */
            body: string;
            /** Options */
            options?: Record<string, never> | null;
        };
        /** QuestionResult */
        QuestionResult: {
            /** Question Id */
            question_id: number;
            /** Given Answer */
            given_answer: string;
            /** Is Correct */
            is_correct: boolean;
            /** Correct Answer */
            correct_answer: string;
            /** Explanation */
            explanation: string;
            skill_tag: components["schemas"]["SkillTagEnum"];
        };
        /**
         * QuestionTypeEnum
         * @enum {string}
         */
        QuestionTypeEnum: "mcq" | "short_answer" | "numeric";
        /** QuizOut */
        QuizOut: {
            /** Questions */
            questions: components["schemas"]["QuestionPublic"][];
        };
        /** QuizSubmitRequest */
        QuizSubmitRequest: {
            /** Answers */
            answers: components["schemas"]["AnswerSubmission"][];
        };
        /** QuizSubmitResponse */
        QuizSubmitResponse: {
            /** Score */
            score: number;
            /** Results */
            results: components["schemas"]["QuestionResult"][];
            /** Skill Breakdown */
            skill_breakdown: components["schemas"]["SkillBreakdownItem"][];
            /** Unlocked Next */
            unlocked_next: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** @default student */
            role: components["schemas"]["UserRoleEnum"];
        };
        /** SkillBreakdownItem */
        SkillBreakdownItem: {
            skill_tag: components["schemas"]["SkillTagEnum"];
            /** Correct */
            correct: number;
            /** Total */
            total: number;
            /** Accuracy */
            accuracy?: number | null;
            /**
             * Insufficient Data
             * @default false
             */
            insufficient_data: boolean;
        };
        /**
         * SkillTagEnum
         * @enum {string}
         */
        SkillTagEnum: "memorization" | "comprehension" | "application" | "analysis";
        /** SubjectOut */
        SubjectOut: {
            /** Id */
            id: number;
            slug: components["schemas"]["SubjectSlugEnum"];
            /** Name Ar */
            name_ar: string;
            /** Name En */
            name_en: string;
        };
        /**
         * SubjectSlugEnum
         * @enum {string}
         */
        SubjectSlugEnum: "english" | "math" | "science";
        /** TokenResponse */
        TokenResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["UserRoleEnum"];
        };
        /**
         * UserRoleEnum
         * @enum {string}
         */
        UserRoleEnum: "student" | "parent";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_subjects_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"][];
                };
            };
        };
    };
    get_path_subjects__slug__path_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["SubjectSlugEnum"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_lessons__lesson_id__quiz_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_quiz_lessons__lesson_id__quiz_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_skills_me_skills_get: {
        parameters: {
            query: {
                subject: components["schemas"]["SubjectSlugEnum"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillBreakdownItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    practice_next_practice_next_get: {
        parameters: {
            query: {
                subject: components["schemas"]["SubjectSlugEnum"];
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    practice_submit_practice_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_chat_sessions__session_id__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_math_math_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_math_math_submit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
