"""Generate frontend DTOs from FastAPI's OpenAPI schemas (no database required)."""
import json
from pathlib import Path

from app.main import app


def ts_type(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema['items'])}>"
    if kind == "object":
        if "properties" in schema:
            required = schema.get("required", [])
            return "{\n" + "\n".join(
                f"  {json.dumps(key)}{'' if key in required else '?'}: {ts_type(value)};"
                for key, value in schema["properties"].items()
            ) + "\n}"
        values = schema.get("additionalProperties")
        return f"Record<string, {ts_type(values) if isinstance(values, dict) else 'unknown'}>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def run():
    schemas = app.openapi()["components"]["schemas"]
    output = "// Generated by: cd backend && python -m scripts.export_api_types\n// Do not edit; source: app/schemas.\n\n"
    output += "\n\n".join(f"export type {name} = {ts_type(schema)};" for name, schema in schemas.items()) + "\n"
    target = Path(__file__).resolve().parents[2] / "frontend/lib/api/schema.ts"
    target.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    run()
