// Generated by: cd backend && python -m scripts.export_api_types
// Do not edit; source: app/schemas.

export type ActivityAnswer = {
  "question_id": number;
  "answer": string;
  "practice"?: boolean;
  "previous_attempt_id"?: number;
};

export type ActivityDay = {
  "date": string;
  "total": number;
  "subjects": Array<SubjectActivity>;
};

export type ActivityProgress = {
  "learned_steps"?: Array<number>;
  "learning_total"?: number | null;
  "draft"?: AnswerSubmission | null;
};

export type ActivityQuestion = {
  "id": number;
  "lesson_id": number;
  "skill_tag": SkillTagEnum;
  "qtype": QuestionTypeEnum;
  "body": string;
  "options"?: Record<string, unknown> | null;
  "number": number;
  "scored": boolean;
  "previous_attempt_id"?: number;
};

export type ActivityState = {
  "questions": Array<ActivityQuestion>;
  "total": number;
  "answered": number;
  "correct": number;
  "scored_total": number;
  "score": number | null;
  "skills": Array<SkillBreakdownItem>;
  "weakest": Array<string>;
  "learned_steps": Array<number>;
  "drafts": Record<string, string>;
  "feedback"?: QuestionResult | null;
  "reflection_saved"?: boolean;
};

export type AnswerSubmission = {
  "question_id": number;
  "answer": string;
};

export type Body_submit_math_math_submit_post = {
  "image": string;
  "question_id": number;
};

export type ChatMessageRequest = {
  "content": string;
};

export type ChatMessageResponse = {
  "reply": string;
  "done"?: boolean;
  "feedback"?: string | null;
};

export type ChatModeEnum = "english_convo" | "science_explain";

export type ChatSessionCreateRequest = {
  "lesson_id": number;
  "mode": ChatModeEnum;
};

export type ChatSessionCreateResponse = {
  "session_id": number;
};

export type HTTPValidationError = {
  "detail"?: Array<ValidationError>;
};

export type LearnerStats = {
  "timezone": string;
  "streak_days": number;
  "correct": number;
  "total_attempts": number;
  "accuracy": number | null;
  "week": Array<ActivityDay>;
  "subjects": Array<SubjectProgress>;
};

export type LessonDetail = {
  "lesson": LessonOut;
  "sections": Array<LessonSectionOut>;
};

export type LessonOut = {
  "id": number;
  "subject_id": number;
  "order_index": number;
  "title": string;
  "objective": string;
};

export type LessonSectionOut = {
  "id": number;
  "order_index": number;
  "heading": string;
  "body_md": string;
};

export type LessonStatusEnum = "locked" | "unlocked" | "completed";

export type LoginRequest = {
  "email": string;
  "password": string;
};

export type MathSubmitResponse = {
  "verdict": MathVerdictEnum;
  "feedback": string;
  "extracted"?: Record<string, unknown> | null;
};

export type MathVerdictEnum = "correct" | "incorrect" | "unreadable";

export type PathNode = {
  "lesson_id": number;
  "order": number;
  "title": string;
  "status": LessonStatusEnum;
  "score"?: number | null;
  "progress"?: number;
};

export type PracticeSetOut = {
  "questions": Array<QuestionPublic>;
};

export type PracticeSubmitRequest = {
  "answers": Array<AnswerSubmission>;
};

export type PracticeSubmitResponse = {
  "results": Array<QuestionResult>;
  "skill_breakdown": Array<SkillBreakdownItem>;
};

export type QuestionPublic = {
  "id": number;
  "lesson_id": number;
  "skill_tag": SkillTagEnum;
  "qtype": QuestionTypeEnum;
  "body": string;
  "options"?: Record<string, unknown> | null;
};

export type QuestionResult = {
  "question_id": number;
  "given_answer": string;
  "is_correct": boolean;
  "correct_answer": string;
  "explanation": string;
  "skill_tag": SkillTagEnum;
};

export type QuestionTypeEnum = "mcq" | "short_answer" | "numeric";

export type QuizOut = {
  "questions": Array<QuestionPublic>;
};

export type QuizSubmitRequest = {
  "answers": Array<AnswerSubmission>;
};

export type QuizSubmitResponse = {
  "score": number;
  "results": Array<QuestionResult>;
  "skill_breakdown": Array<SkillBreakdownItem>;
  "unlocked_next": boolean;
};

export type RegisterRequest = {
  "name": string;
  "email": string;
  "password": string;
  "role"?: UserRoleEnum;
};

export type SkillBreakdownItem = {
  "skill_tag": SkillTagEnum;
  "correct": number;
  "total": number;
  "accuracy"?: number | null;
  "insufficient_data"?: boolean;
};

export type SkillTagEnum = "memorization" | "comprehension" | "application" | "analysis";

export type SubjectActivity = {
  "subject_id": number;
  "count": number;
};

export type SubjectOut = {
  "id": number;
  "slug": SubjectSlugEnum;
  "name_ar": string;
  "name_en": string;
};

export type SubjectProgress = {
  "id": number;
  "slug": SubjectSlugEnum;
  "name_ar": string;
  "name_en": string;
  "correct": number;
  "total_attempts": number;
  "accuracy": number | null;
  "completed_lessons": number;
  "total_lessons": number;
  "next_lesson": PathNode | null;
  "lessons": Array<PathNode>;
};

export type SubjectSlugEnum = "english" | "math" | "science";

export type TokenResponse = {
  "token": string;
  "user": UserOut;
};

export type UserOut = {
  "id": number;
  "name": string;
  "email": string;
  "role": UserRoleEnum;
};

export type UserRoleEnum = "student" | "parent";

export type ValidationError = {
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
  "input"?: unknown;
  "ctx"?: Record<string, unknown>;
};
